import { LanguageProvider } from "@inlang/paraglide-js-adapter-next";
import { languageTag } from "@/paraglide/runtime.js";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import * as m from "@/paraglide/messages.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider>
      <html className="uui-dark" lang={languageTag()}>
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </LanguageProvider>
  );
}
