import { LanguageProvider } from "@inlang/paraglide-js-adapter-next";
import { languageTag } from "@/paraglide/runtime.js";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import * as m from "@/paraglide/messages.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* TODO check if the telegram is correct */
const socialLinks = [
  { href: m.leaderboard_footer_socialLinks_x_href(), iconUrl: "/x.svg" },
  {
    href: m.leaderboard_footer_socialLinks_discord_href(),
    iconUrl: "/discord.svg",
  },
  {
    href: m.leaderboard_footer_socialLinks_telegram_href(),
    iconUrl: "/telegram.svg",
  },
  {
    href: m.leaderboard_footer_socialLinks_github_href(),
    iconUrl: "/github.svg",
  },
  {
    href: m.leaderboard_footer_socialLinks_linkedin_href(),
    iconUrl: "/linkedin.svg",
  },
  {
    href: m.leaderboard_footer_socialLinks_youtube_href(),
    iconUrl: "/youtube.svg",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider>
      <html className="uui-dark" lang={languageTag()}>
        <body className={inter.className}>
          <NavBar />
          {children}
          <Footer
            footerIcon={{
              src: "lilypad-logo.svg",
              alt: "Lilypad logo",
              href: "#top",
            }}
            socialLinks={socialLinks}
          />
        </body>
      </html>
    </LanguageProvider>
  );
}
