import { LanguageProvider } from "@inlang/paraglide-js-adapter-next"
import { languageTag } from "@/paraglide/runtime.js"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* TODO check if the telegram is correct */
const socialLinks = [
  { href: "https://twitter.com/lilypad_tech", iconUrl: "/x.svg" },
  { href: "https://discord.gg/zWYTNZqB", iconUrl: "/discord.svg" },
  { href: "https://t.me/lilypadnetwork", iconUrl: "/telegram.svg" },
  { href: "https://github.com/Lilypad-Tech", iconUrl: "/github.svg" },
  {
    href: "https://www.linkedin.com/company/lilypad-network/",
    iconUrl: "/linkedin.svg",
  },
  {
    href: "https://www.youtube.com/@LilypadNetwork/featured",
    iconUrl: "/youtube.svg",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LanguageProvider>
   <html className="uui-dark" lang={languageTag()}>
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer
          footerIcon={{
            src: "lilypad-logo.svg",
            alt: "Lilypad logo",
            href: "#top",
          }}
          socialLinks={socialLinks}
        />
      </body>
    </html>
 </LanguageProvider>
  );
}
